### ISSUE TITLE
 Figure out a plan for codejail PR tests

### ISSUE THREAD

**Issue by kdmccormick** [openedx/codejail#121]
Problem: codejail tests and quality checks are run on edX's https://build.testeng.edx.org Jenkins instance. Moving the tests is non-trivial because they involve setting up and testing an AppArmor profile. It isn't clear whether that'd be doable with GitHub Actions.

________________________
Some Discovery Notes (copied from https://github.com/openedx/decoupling/issues/100):

It's possible to startup a github actions runner with a specific ApArmor profile: https://docs.docker.com/engine/security/apparmor/

However, there is no way currently to specify an AppArmor profile on a `container-job` in github actions: https://docs.github.com/en/actions/using-containerized-services/about-service-containers

We could do this on custom github action runners that we operate if we go down that route but there is currently no way to validate the AppArmor side of the codejail framework without some custom test runner.

There is an argument to be made that codejail has some features and AppArmor has some features and we should just test them independently.  While that feels technically correct, I'm not sure if we have enough other gates to ensure that the overall expectation of security when operating codejail in production can be guaranteed.

____________________

Further notes:

After speaking about this with @feanil @nedbat @kdmccormick @Carlos-Muniz and @ormsbee . We decided to defer this until after the repo has move to the openedx org. It should still be done as a part of the decoupling but we no longer consider it a blocker for the repository transfer. Once the repository has moved to the openedx org, we can re-visit this and figure out how we want to maintain this repo and its tests moving forward.

**Comment by jmakowski1123** [comment]
Target Q2. Suggest input from Jeremy Bowman.

**Comment by sarina** [comment]
Hey team, how are people feeling about this ticket currently?

**Comment by kdmccormick** [comment]
Looks like Arbi-BOM resolved this back in March: https://github.com/openedx/codejail/pull/128  🎉
