### ISSUE TITLE
Test codejail on Ubuntu 22.04

### ISSUE THREAD

**Issue by feanil** [openedx/codejail#186]
This repository is using Ubuntu 20.04 for testing. That version of Ubuntu will be out of support before Teak. Therefore this repo needs to be updated to testing with Ubuntu 22.04 before Sumac is cut to allow everyone sufficient time to switch to the new version.

Update this repository to test with Ubuntu 22.04 so that we can make the switch.

- [x] Tests are run and passing on Ubuntu 20.04 and 22.04
- [x] If major changes were needed and this is a library, a new version is published to PyPI or NPM

Note: In some cases, it may not make sense to test with both the old and the new version.  For example, if the workflow is running linting or publishing to a package manager.  In these cases, simply update the workflow to run on the newer version or opt to set it to `ubuntu-latest` instead if it doesn't matter what version it's running on.  If you're unsure, reach out to the maintenance working group in [#wg-maintenance](https://openedx.slack.com/archives/C03R320AFJP) in slack for guidance.

Known affected workflow files:

- .github/workflows/ci.yml
- .github/workflows/pypi-release.yml

**Comment by feanil** [comment]
@MoisesGSalas what's the state of this ticket, will you be able to complete it before the Sumac cut (Oct 23) or do you need more help to be able to land it by then?

**Comment by MoisesGSalas** [comment]
Hi @feanil, I will be working on this this week. I opened #193 just to see a CI run and got a few errors.

If by the end of the week I'm facing any troubles I will ask for help.

**Comment by feanil** [comment]
@MoisesGSalas ideally, we should run tests on both Ubuntu 22.04 and 24.04 so that people can use either and we can be sure that codejail will work properly in them.

**Comment by MoisesGSalas** [comment]
Hi @feanil, I've been having trouble with apparmor in newer ubuntus, do you know how can I ask for help?

In ubuntu >= 22.04 I've noticed some of the checks are failing (the sandbox binary can spawn children proceses and can access the network). I tried comparing the profiles used on newer versions but didn't find anything useful. I guess the biggest change would be the version of apparmor itself (2.x in Focal, 3.x in Jammy and 4.x in Noble)?

**Comment by feanil** [comment]
Hi @MoisesGSalas I can take a look at that.  I've fought with this system enough times 😂

**Comment by feanil** [comment]
We're not all the way to 24.04 but https://github.com/openedx/codejail/pull/201 added support for 22.04, further investigation will be needed to add 24.04 support.

**Comment by feanil** [comment]
@MoisesGSalas I've updated this ticket to be for 22.04 support. Can you create a separate ticket for adding 24.04 support and spend some time on that in the next few weeks, perhaps you'll have some luck with it, I can also spend some time on it but given how tricky it was to debug, it would be great if you can also take a look at it.

**Comment by feanil** [comment]
The 22.04 support was added as a part of https://github.com/openedx/codejail/pull/201
